name: news_app_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #icon
  ionicons: ^0.1.2

  #state management
  flutter_bloc: ^8.1.2

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^7.6.0
  
  #dateFormat
  intl: ^0.18.1

  #Database
  floor: any
  sqflite: ^2.4.2

  #make request to api
  retrofit: ^3.0.1

  # Firebase
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.6.5

  #Hooks
  flutter_hooks: ^0.18.3

  #chached image 
  cached_network_image: ^3.2.0
  path_provider: ^2.1.5
  image_picker: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  retrofit_generator: 3.0.1+1
  floor_generator: 1.2.0
  build_runner: 2.1.2
  flutter_launcher_icons: ^0.12.0

dependency_overrides:
  win32:
    path: third_party/win32

flutter:

  uses-material-design: true

  assets:
    - assets/logo/logoSymmetryNews.png

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo/logoSymmetryNews.png"
